### ISSUE TITLE
wordcount.doc 步骤遗漏

### ISSUE THREAD

**Issue by pheicloud** [ffbh/hadoop#1]
1、将该文件传输到hdfs执行
hadoop  fs  -put  wc.txt  hdfs://master:9000/user/root   
2、执行mapreduce将结果保存于同级目录out中执行
hadoop jar hadoop-mapreduce-examples-2.7.4.jar wordcount hdfs://master:9000/user/root hdfs://master:9000/user/root/out

**Comment by ffbh** [comment]
好的，已更新

**Comment by pheicloud** [comment]
:ok_hand:
